### ISSUE TITLE
Cant run

### ISSUE THREAD

**Issue by RayyanRS6** [Daymenion/two_body_simulation_in_python_and_c#1]
How can I run this on my pc?

**Comment by Daymenion** [comment]
if you have c compiler like gcc in your computer you can run c file, if you have python interpreter in your computer you can run python files. Check the file names produce by code maybe there's difference between viewer used and controller produced, and that's it. If you don't know how to run a python/c code or handling with errors you should watch some tutorials on YouTube.

**Comment by RayyanRS6** [comment]
i can use either python or c code?

or are these codes integrated with eachother?
